name: Deployment

on:
  push:
    branches: 
    - main
    - staging
    - develop

jobs:
  stylelint:
    name: CSS Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node dependencies
      run: npm install

    - name: Build Node assets
      run: npm run lint-style

  eslint:
    name: JavaScript Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node dependencies
      run: npm install

    - name: Build Node assets
      run: npm run lint-js

  phpcs:
    name: PHP Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Composer dependencies
      run: composer install

    - name: Lint Coding Standards
      run: composer run lint

  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Composer dependencies
      run: composer install

    - name: Static Analysis
      run: composer run static

  deploy:
    name: Deployment
    runs-on: ubuntu-latest  
    needs: [stylelint,eslint,phpcs,phpstan]

    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node dependencies
      run: npm install

    - name: Build Node assets
      run: npm run build

    - name: Install Composer dependencies
      run: composer install --no-dev -o

    - name: Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v2.3.5
      with: 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
        CACHE_CLEAR: TRUE
        TPO_SRC_PATH: "."
        TPO_PATH: "wp-content/themes/jump/"
        # Production
        PRD_BRANCH: main
        PRD_ENV: jumpcommunity
        # Staging
        STG_BRANCH: staging
        STG_ENV: jumpcommstg
        # Develop
        DEV_BRANCH: develop
        DEV_ENV: jumpcommdev