name: Test Pull Request

on:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install

    - name: Lint Coding Standards
      run: composer run lint

  phpstan:
    runs-on: ubuntu-latest
    needs: phpcs

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install

    - name: Static Analysis
      run: composer run test:static

  # phpunit:
  #   runs-on: ubuntu-latest
  #   needs: [phpcs,phpstan]

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Set PHP version
  #     uses: shivammathur/setup-php@v2
  #     with:
  #       php-version: '7.4'
  #       coverage: none
  #       tools: composer:v2

  #   - name: Install dependencies
  #     run: composer install && npm install
    
  #   - name: Build
  #     run: npm run build

  #   - name: Test
  #     run: ./vendor/bin/phpunit -v
    
  # cypress:
  #   runs-on: ubuntu-latest
  #   needs: [phpcs,phpstan,phpunit]

  #   strategy:
  #     matrix:
  #       core:
  #         - {name: 'WordPress: latest', version: 'latest'}

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Build asset
  #     run: npm run build

  #   - name: Set the core version
  #     run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}

  #   - name: Set up WP environment
  #     run: npm run wp-env start

  #   - name: Test
  #     run: npm run cypress:run