name: Test

on:
  pull_request:

jobs:
  stylelint:
    name: CSS Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node dependencies
      run: npm install

    - name: Build Node assets
      run: npm run lint-style

  eslint:
    name: JavaScript Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node dependencies
      run: npm install

    - name: Build Node assets
      run: npm run lint-js

  phpcs:
    name: PHP Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install

    - name: Lint Coding Standards
      run: composer run lint

  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install

    - name: Static Analysis
      run: composer run test:static
