name: Test

on:
  pull_request:

jobs:
  stylelint:
    name: CSS Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node dependencies
      run: npm install

    - name: Build Node assets
      run: npm run lint-style

  eslint:
    name: JavaScript Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node dependencies
      run: npm install

    - name: Build Node assets
      run: npm run lint-js

  phpcs:
    name: PHP Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Composer dependencies
      run: composer install

    - name: Lint Coding Standards
      run: composer run lint

  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Composer dependencies
      run: composer install

    - name: Static Analysis
      run: composer run static
